name: Build and Test
on: [push]
jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup compiler
        uses: aminya/setup-cpp@v1
        with:
          vcvarsall: true
          cmake: true
          ninja: true
          bazel: true
          compiler: gcc-15
      - name: build
        run: bazel build //...

      
